# Generated by Django 5.2.7 on 2025-10-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_group_description_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='headline',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.CharField(default='', max_length=255),
        ),
    ]
