# Generated by Django 5.2.7 on 2025-10-24 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=255)),
                ('StreetName', models.TextField()),
                ('leisure', models.CharField(choices=[('pitch', 'Pitch'), ('stadium', 'Stadium'), ('sports_centre', 'Sports Centre')], default='pitch', max_length=20)),
                ('name', models.TextField(blank=True, null=True)),
                ('price_per_hour', models.IntegerField(default=250000, help_text='Price per hour in IDR (e.g. 250000)')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.PositiveIntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('GOPAY', 'GoPay'), ('PAYPAL', 'PayPal'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.venue')),
            ],
            options={
                'ordering': ['-date', 'start_time'],
                'unique_together': {('venue', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
