# Generated by Django 5.2.7 on 2025-10-22 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=255)),
                ('StreetName', models.TextField()),
                ('leisure', models.CharField(choices=[('pitch', 'Pitch'), ('stadium', 'Stadium'), ('sports_centre', 'Sports Centre')], default='pitch', max_length=20)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
