# Generated by Django 5.2.7 on 2025-10-23 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='price_per_hour',
            field=models.IntegerField(default=250000, help_text='Price per hour in IDR (e.g. 250000)'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.PositiveIntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('GOPAY', 'GoPay'), ('PAYPAL', 'PayPal'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.venue')),
            ],
            options={
                'ordering': ['-date', 'start_time'],
                'unique_together': {('venue', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
