# Generated by Django 5.2.7 on 2025-10-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venues',
            new_name='Venue',
        ),
    ]
