# Generated by Django 5.2.7 on 2025-10-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_venue_price_per_hour_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
