# Generated by Django 5.2.7 on 2025-10-26 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('target_type', models.CharField(choices=[('venue', 'Venue'), ('review', 'Review'), ('post', 'Post'), ('comment', 'Comment'), ('community', 'Community')], max_length=20)),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate / Harassment'), ('spam', 'Spam / Ads'), ('false_info', 'False or Misleading Info'), ('scam', 'Scam / Fraud'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'indexes': [models.Index(fields=['content_type', 'object_id', 'status'], name='reports_content_0d0dd9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('reporter', 'content_type', 'object_id'), name='uq_open_report_per_user_target')],
                'unique_together': {('reporter', 'content_type', 'object_id', 'status')},
            },
        ),
    ]
