# Generated by Django 5.2.3 on 2025-10-25 18:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'content_type', 'object_id', 'status')},
        ),
    ]
