# Generated by Django 5.2.7 on 2025-10-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='object_id',
            field=models.CharField(max_length=64),
        ),
    ]
