# Generated by Django 5.2.5 on 2025-10-26 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reports', '0002_alter_report_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open'), ('status', 'under_review'), _connector='OR'), fields=('reporter', 'content_type', 'object_id'), name='uniq_open_or_review_report_per_user_target'),
        ),
    ]
