# Generated by Django 5.2.5 on 2025-10-26 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reports', '0003_report_uniq_open_or_review_report_per_user_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='uniq_open_or_review_report_per_user_target',
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('reporter', 'content_type', 'object_id'), name='uq_open_report_per_user_target'),
        ),
    ]
