# Generated by Django 5.2.6 on 2025-12-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_uniq_open_or_review_report_per_user_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('venue', 'Venue'), ('review', 'Review'), ('post', 'Post'), ('comment', 'Comment'), ('community', 'Community')], max_length=20),
        ),
    ]
